### ISSUE TITLE
Issue with the npx script

### ISSUE THREAD

**Issue by Acemavie234** [remorses/planetscale-to-supabase#2]
I am trying to migrate from planetscale and all has been succesfull until this. I have docker desktop installed and when I run docker --version on cmd it returns fine. But when I run the script it says that I do not have docker installed. I originally removed the part that ran docked --version but then I realized that docker is used in the migrate script too. And after pressing enter at the step where you specify the supabase url I get greeted  with this error. Is there something  that I'm  missing?

<3>WSL (2209) ERROR: CreateProcessEntryCommon:505: execvpe /bin/bash failed 2
<3>WSL (2209) ERROR: CreateProcessEntryCommon:508: Create process not expected to return
Error: Could not run 'docker': code 1
    at ChildProcess.<anonymous> (C:\Users\kasutaja\AppData\Local\npm-cache_npx\5c9413c17d99d699\node_modules\migrate-planetscale-to-supabase\dist\index.js:262:27)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

**Comment by remorses** [comment]
Maybe you don't have docker installed inside wsl

https://stackoverflow.com/questions/63497928/ubuntu-wsl-with-docker-could-not-be-found

**Comment by Acemavie234** [comment]
I got it working. But then I realized postgres is so different and weird. And I have to rewrite half of my API with it. So I'll probably need to find a good mysql alternative
